### ISSUE TITLE
UnionPath.checkArraysMatch matches empty array against anything

### ISSUE THREAD

**Issue by littlej541** [McModLauncher/securejarhandler#39]
As title suggests. Is this the intended behavior?

https://github.com/McModLauncher/securejarhandler/blob/331438e6bc07c48f3bb9b1dfb33415c01043048e/src/main/java/cpw/mods/niofs/union/UnionPath.java#L175-L183

Since a zero-length array returns `length` as 0, the loop is entirely skipped over and `true` is always returned.

**Comment by marchermans** [comment]
At the moment yes, this is intended behavior. Is there a problem with a use case you are having?

**Comment by littlej541** [comment]
No, I was calling `net.minecraft.server.packs.resources.ResourceManager:listResources` in a Forge mod with the `Predicate` argument set to always return true and got some strange results. Investigating lead me to this and I wondered if it was supposed to be that way. My actual issue was solved by passing in a more limiting `Predicate`.

Since it is intended, I'll go ahead and close this.
